name: notify-failure

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - uses: 8398a7/action-slack@v3
      with:
        status: custom
        custom_payload: |
          {
            username: 'e2e-api-tests',
            icon_emoji: ':octocat:',
            attachments: [{
              color: 'danger',
              blocks: [
                  {
                  "type": "section",
                  "text": {
                      "type": "mrkdwn",
                      "text": `:x: Python SDK CI failed`
                  },
                  {
                  "type": "actions",
                  "elements": [
                      {
                      "type": "button",
                      "text": {
                          "type": "plain_text",
                          "emoji": true,
                          "text": "Python SDK CI"
                      },
                      "style": "primary",
                      "url": `https://github.com/airtop-ai/airtop-python-sdk/actions/runs/${{ github.run_id }}`
                      }
                  ]
                  }
              ]
            }]
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.AIRTOP_SLACK_WEBHOOK_URL }}